---
- name: Homelab Deployment
  hosts: homelab
  become: true
  roles:
    - { role: bootstrap, tags: ["bootstrap"] }
    - { role: mergerfs, tags: ["mergerfs"] }
    - { role: cloudflared, tags: ["cloudflared"] }
    - { role: host_cron, tags: ["host_cron"] }
    - { role: backup, tags: ["backup"] }
    - { role: service_manager, tags: ["service_manager"] }
    - { role: notes, tags: ["notes"] }

  tasks:
    - name: Flush handlers to apply service changes
      ansible.builtin.meta: flush_handlers
    - name: Run verification
      ansible.builtin.include_role:
        name: verify
        apply:
          tags: ["verify"]
      tags: ["verify"]
