---
all:
  hosts:
    homelab:
      ansible_host: 100.79.210.89
      ansible_user: caleb
      ansible_python_interpreter: /usr/bin/python3.11
      ansible_become_password: "{{ ssh_user_password }}"
