vpn_secret:
    provider: ENC[AES256_GCM,data:llbO4F1XlA==,iv:NsQktJ1YvZ3gf8G6mBSXhVfeDcoFehRvSfr9thIR0Ws=,tag:jTOT4JR8KK61xhLRgDmzWg==,type:str]
    private_key: ENC[AES256_GCM,data:bKdrfQyMUKR6bmzqHiBVzhTtybGC6SDpPdjdhdG39KbVNvHResc7P0EHTW8=,iv:LW5NvuHxCqN3rHfhgXPbkj0FjAT2qQnt4gOF5vcgCOM=,tag:m78A18AnIvgWDsop+8GW1A==,type:str]
    addresses: ENC[AES256_GCM,data:oj5uY67ssV/6syf7oTT/,iv:oQzeCpm+HTmi1E1YHBjjgsrolqPeBEaaGF4VOGNgyJM=,tag:Gb3vY1BZVjYwbhq1OiuuRw==,type:str]
admin_password: ENC[AES256_GCM,data:jAnjgRfQPA==,iv:U54jsTXjiUeKwq/Bp7vF9XiO0X2Y7VxjDk30epAqfEE=,tag:gDecdvuja1CSxmMQLrBDuw==,type:str]
api_keys:
    sonarr: ENC[AES256_GCM,data:cQmZaXICrFhWUduJPHn1INZ5tUd6W38CtFxZjpIxlek=,iv:nq3RJCm2cgRA2c6proqrTtAk4CE9cn8iIsXNZdpMs/c=,tag:ZCW8WkkXwaqwIuq2/h/oiw==,type:str]
    radarr: ENC[AES256_GCM,data:Op/UeYvUo27gMw7igrzwTU0aS2UK+fhNqacbNl3Yfd4=,iv:q2Y7UtFn++ndxV1qxqcomv7WWHlEoNvxq9U/Cn86e40=,tag:qiRFsp7Kt4xqkLUbf4p3ig==,type:str]
    prowlarr: ENC[AES256_GCM,data:n13PCc8SGOax5pRuIvBbLCXhPnpSZtIR9yVRJSi4isI=,iv:ATbWcOWLkq9RFL7k4ZIwH5InZfNcF5VHctK7Tn0Cdvk=,tag:YMHeuvRv/S4y3frDCLTBtg==,type:str]
overseerr_secret:
    vapid_private: ENC[AES256_GCM,data:NepbO5YGEcxMqZWDvibqWMj63q+GiD2A9TUEJF6E1A1fxZ79ja1Up6Pmsg==,iv:3cwMd8ehP8eUSQ2R+Ndm3Rkl4OQ3iv8n8jCrUa5NRl4=,tag:hO34vOaI7cZE2CADUJ7X8w==,type:str]
    vapid_public: ENC[AES256_GCM,data:Ad43c8Xhn0w5GxStJaCcKVsUyrFwtdhEsSE1SRn3zUk5go0iii0cyDGxYLeeHrLpUIgWeAbCrah3zGhX0Z0++kjiksSl7Y99sAFJ7WwHywwAT3YKoDO0,iv:De2jtPdPZw0qs1KyGt00kmKjZsqPthx0P6EQah6LeB8=,tag:qCSewKBcs6XJuQGCthymxQ==,type:str]
    client_id: ENC[AES256_GCM,data:yuiT2RNRcf9z0XRmuyE9VtkH3zFJu6EVTw3TILOWoi7kxWxH,iv:gkfBuxco1TP7KsASGUUprrMzGKGM3CrlhtcUNv0aEc8=,tag:JeG518agBJZ0vAczqZAMjQ==,type:str]
    plex_machine_id: ENC[AES256_GCM,data:o6WKroGjEFadX9cl/qJYG4usssYnW6Br6gaYsydj52oc5gtyte0kNw==,iv:4uzrkhUr3Crbjy1OeR7MD8n2KIS1nTL9b0o+52EhksQ=,tag:aXCxL8Dh+1npdiAJ/iUiNA==,type:str]
    plex_name: ENC[AES256_GCM,data:nauTYvXMrh7i,iv:/JshLce1BJIOvxw9170EHluF8mPbiXWPMrjb0UQv8/U=,tag:bYFHZB7W8ikV+BtOlki1ug==,type:str]
    api_key: ENC[AES256_GCM,data:cYcEalzrtspSRtDl8RXqvouw1AtD8dZBJaeeAuXF9RGTMjSvXxVL3lNR15gJSm8TkVJgfvVb+1WuNaxTTlCrpJEhK8c=,iv:t/IfQhF+Fzk3WDW37x5TSWBS3ddCgBXMHnQsd8MREPQ=,tag:GRxAk85B0k4wCgLilRe/lQ==,type:str]
    users:
        - email: ENC[AES256_GCM,data:8E8Fm4n70kHopWdJH7PVZF/6Xw7MlGl6wkd7,iv:h8ITsNb9qKBvG3+jkjrXRjcMO88FmrpSmpfllKCbUvM=,tag:OX7uOJF/fXomXBQ5qsbqKw==,type:str]
          permissions: ENC[AES256_GCM,data:sg==,iv:phYIc5oCJy1x2+DRPAySI5VtkIyjn8v9f0PXG0Ppj4E=,tag:i87jhU/dTkiaF2/IT92wvA==,type:int]
        - email: ENC[AES256_GCM,data:rnh0OOR84tGw5FE3ckMlNw==,iv:7upf0xpl407ZwwQKzSLh6n260knv99V2oJtqUPxrHA4=,tag:bmTxe40XZqvnPQ1uXEeDdA==,type:str]
          permission: ENC[AES256_GCM,data:4c0=,iv:c5RdL6jX6k+CcLqq1d3RRJZDmFjK2OxrmvsWDCZepgY=,tag:E6ZcKyv7MtWmpaSSf3i0aw==,type:int]
          label: ENC[AES256_GCM,data:iV/zTXTVROs/,iv:CQDBin8iuRv6xl3wlrnf1PjfZvuBq6MTMMt6vlKdEfs=,tag:o2I+Ieb1lyC2p4RLehIhSg==,type:str]
plex_secret:
    machine_id: ENC[AES256_GCM,data:WCkbSscr9E9Vl9rzQeCSY0k24r2d/OIgV/5RLr9YbSsijJQ3,iv:JdpN20oDepT/JpLwzlDhkOgweiX5UxdDdXQnAdgK0eA=,tag:5ybigcyTvkxSzHU0uwwf/A==,type:str]
    claim_token: ENC[AES256_GCM,data:xsQmDnV0yl92hMtJZ+jtpn4mFT+SwvGX3/U=,iv:dya23cUl9Wq6gjn5nzEkV6GDKCjL7ErYQ4zPx378mdU=,tag:aDEP85Q3JTAbI47vrizllw==,type:str]
    online_token: ENC[AES256_GCM,data:rWxEu3AUvkZnURs5We3oWm0tHjg=,iv:vS1Bt2TiqB8iQc6KCZuvcQvs3O3rOoknfX/AbP+ycbA=,tag:Fh+0YHjKjEcila3+FfIt2g==,type:str]
    processed_machine_id: ENC[AES256_GCM,data:zH1ZKL/G8mlf9APZB8IvQkqZfNPRsjIm+xm2RWvPq+p6k7MiHCkWIw==,iv:NZD2dt02F8fceb+cP4faK+KJ175Hse8S31Uk0/GZqiM=,tag:sy9nE9Kmtgo+KcYtDjTIpA==,type:str]
    anonymous_machine_id: ENC[AES256_GCM,data:9TMez2+2Ta99fo5RmufVZjY4Dnw3JRWW30h89MbqQ4SdpYEP,iv:esii/ea8QoTDmxfOaAM9LJ/fBTdWDe7Ck06cCN4hxW8=,tag:tubpVvf08Wkzpn/9ctUUMg==,type:str]
    online_username: ENC[AES256_GCM,data:0Y9KUslAjLVjHw==,iv:ROpSZWxXI7zROSYL/ARQLF8/Mjw5KBoEU4Lue14nByY=,tag:e+1wPzJfBkU3A+PF7t9P9Q==,type:str]
    online_email: ENC[AES256_GCM,data:SYtHQ2Pwl/e1/3K8Jz1fnOa/r8YrrBVoPmaw,iv:KKL3oWEqfPF6B0V0PH5qbbqV2EdsIC5IVI5oLtsf/TI=,tag:oBBumvm6stW6qeq9TeVttQ==,type:str]
tmdb_api_key: ENC[AES256_GCM,data:ayParlkHClq6gnqE0Kz7GkDfyVvDHSu1z25nxX9Sq3Q=,iv:Ww0XgSX7dzXxMSPOGpcERxtzJ0mND2S6xjakci7699w=,tag:w4Yua1fkCsqVVkLdcz1zWg==,type:str]
ssh_user_password: ENC[AES256_GCM,data:ymb8Al8=,iv:WruqvHRm061/dvCvEeB01umSwVHa/gieuq3GNt+93Q8=,tag:rFIP9bn1IBJsBVN4lnhAcg==,type:str]
cleanuparr_secret:
    password_hash: ENC[AES256_GCM,data:E5vVbAx7hLv7X+cyh476oBFFax2ICg==,iv:I9PdKrHnRT7z0UFg1+213AbBgOE4FGx50CWdF2zMNCc=,tag:Xr0shni0Nz0ja12N7jdZhg==,type:str]
    api_key: ENC[AES256_GCM,data:9hqopwPs6dZwVJsrifP1iD943gDk+2qWGAu3Xt7uwt2oAvTLEkDfcPUWBojQ3xqPG/M1Qh4mgHdWvTEADg1eXQ==,iv:hYoGhgW30heKcmaqTUlpfq9JGEMZ8e4D+7r70aRtTzI=,tag:1zp5QWNox+l+laCbRTIWmg==,type:str]
anki_secret:
    sync_user1: ENC[AES256_GCM,data:yIPIMT31JhkiP4i/Toml8UIlwTISI3kMnbA=,iv:7vn2RKCChUs39TIdzvgQ3Te+DLWCGzc6Dt013xB3pRo=,tag:gYBg9L7a6B1I1APNUdLoAw==,type:str]
sops:
    age:
        - recipient: age1wevrc2du2esx4p6td6ghn0rrw8ldg5zxszruxpn98q5ucj9ykqusduyt4m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaEg5ZTZnTGRNRkVpcnp5
            ekxhZlRWUk8vSnBtZGlLSi9PS3RSTzljTlQ4Cm9GU2NvY29tSlhiWG8ybmt2bmpl
            WUdhZ1FtSmdmVFlEai9zeUhhT0xCZkUKLS0tIHgyczNWaXBxUjY3L1dVL2IyM3F6
            VzBJN2V6bkNPK3JtdUp0Mk5pUGg3TTQKByENa9tHEj7qB/Vdob/kkokNHkoZKw1X
            N6IoGOoYXfIQgfQ2CMGMG09nzXtyZtgb6t6YMrYOmDcWY9j35yl2KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T16:35:14Z"
    mac: ENC[AES256_GCM,data:l7vA+PmSs/ilf6dQBj0sSSfuLO1ccXtkNxOoiCffrW9rgBKaQX36jXt8JQmQyOnCJaL0B2O+HlSwpqP35K8mN0Lzm/XrddB3q94Q92W4UqP7NvISSlmXoKBlwnXqmAxpULTiNZRTPmLGRChDIx7SBrRxZcJNzzIp0sa7wgAGjzA=,iv:vQGtTPbVVLZggkh6G9XjvN0w/ezBdTnqgFlBlTluiMw=,tag:8/I9tIu9VDdZhXTvEYWWsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
