vpn_secret:
    provider: ENC[AES256_GCM,data:Pp9lW5Hz,iv:liOpvtQOw+Y+frETDyFAKj31ZRqPsEwL5H4amtDr+Zc=,tag:aThTwF2LtN+dsyRkiCOTCA==,type:str]
    private_key: ENC[AES256_GCM,data:SWr71FnykXl89ipChfILXnraLNwCQzzgQ0GpNuAUrEUwBnLkjTewfeTaiLo=,iv:nEE7n9e6HcxAFOm2IrU2EMTLR2lAZBbXwAJI/SeyJUQ=,tag:Swv3aC1aUOwVYJ8NIO0uMQ==,type:str]
    addresses: ENC[AES256_GCM,data:wepfmZfyS18uONA=,iv:QrBVfRacSZrIaX/j6qyVcDxKMflWB+ZaO/IUSKktIgI=,tag:fs1ZdTGXhSsZfLaxeI3oYQ==,type:str]
admin_password: ENC[AES256_GCM,data:EWnHx3e2Vg==,iv:MeTHxD5I1rYkF0Q3qCRma46MUZvFALl7cZyB6ye0ceI=,tag:lgWvaFgxbkhhvaJGQRyMhA==,type:str]
api_keys:
    sonarr: ENC[AES256_GCM,data:PNJGN1Eb+LVHzFhGjw42veEnEYlf3JnTrtvWCNEztMk=,iv:rbWjTr5MNJhx2T8fRZ1v6xZ69B6kincIWJPXR0LZ0JE=,tag:zT1cUyk9D+y7tW1+LBQ8Ow==,type:str]
    radarr: ENC[AES256_GCM,data:yVq6SK1egvcQ0zJ9EXxXuJ9uzOqUzbhkTAXU6U+D80Y=,iv:5tn8+3XHtbLpy3xp3g8pU5ibD9I4E3iyzJa3hEGpsZo=,tag:oRr1F7ESrPd6H3rvHnSgfQ==,type:str]
    prowlarr: ENC[AES256_GCM,data:Z9ThRpzHbzBKLr0luApioAJim4j2BQAiD/kL/fDVGhc=,iv:VTI+vBytR7iNT8M5TnAUQyP3w5PsVjul6yZatWYd/Q0=,tag:FgrL3dD+HxMrrKkjJds64A==,type:str]
seerr_secret:
    vapid_private: ENC[AES256_GCM,data:oPLz+GUC4V0Fm19zgQF+VTyXaWjCjcYW7nTU0Hs6BKyhZgSztDi/19jamw==,iv:VM2nYi4t/LFkOqGwLjeGgniH6CPBuKaNGBywN9xW/WE=,tag:ZVQiNFAmJx/9cCP4p0/EiA==,type:str]
    vapid_public: ENC[AES256_GCM,data:DVIbk3Jtl8nw647JnrDvNV93DzUDN4IEBxKYT3GzvhGJk5vuYRvInANXORP1mFu6t7Ex23lfWf42mbDzqoyRQTUq1bmaaF0iYRXesot3IV5am03ZvcpK,iv:yWJd4jLz4rhHTNtezaANSc6WgS1EkTZzePLa85SvWFI=,tag:+iOc/nw8IirsU+B5ejs/Yw==,type:str]
    client_id: ENC[AES256_GCM,data:lnf1a1fd1sJ43c0vLFWa3vWTWqw7e1LPMZ2aiIA7Tm1lUYH4,iv:wm0G5BrRczNPBBXZDBxYmMfMU3DRQ0MFeaGdxkJGHxY=,tag:TEXpUvwkD+RBWH+yUidHfQ==,type:str]
    plex_machine_id: ENC[AES256_GCM,data:7f4HnnEymAbM6RdFrhfs34/DKOoVRqWlrbUG2VgjN9GVxN2iXwGaNw==,iv:FC9FLIQnXbv+8wsH1hOyZc83xq/zM/2doz5e/SSEReM=,tag:5wuDgjBQe9PX+v+6BfTWug==,type:str]
    plex_name: ENC[AES256_GCM,data:Kmuev7mL1Yt+,iv:dte/xrZ6oZl24ylJM0XvLINKQOBmlDuqElsA1FjRKCA=,tag:nk0rqpQDv9iZE18DZJ2VMQ==,type:str]
    api_key: ENC[AES256_GCM,data:zV605RO2mASeMg0WhVvar+wQbYZK3XP0TVedmYJ/yQaQ/5s8yySscLu6TvQdBk5o4z5ziLfxGfZesUlV6rKr6L6Xcg0=,iv:JHdq0kr5rxSZ9jD8JkXAtSFx1Lt8H601Ny0z7aRlfB8=,tag:kl9uY9MRm4T9j0FbiJh+nQ==,type:str]
    users:
        - email: ENC[AES256_GCM,data:5RWC+28IMRaBm6qXEvdymHrM6SEdDwaap0vg,iv:ze6oLFQPxxHPqocZB+baZPflgZ+bXpJByxWOVn/xPD4=,tag:ngMxJwe4U1qNqav5Lg2g0g==,type:str]
          permissions: ENC[AES256_GCM,data:sA==,iv:Im5FsDjYUaGjr/6RG6tKEb8zZO64GE8DYbuUGDGSWIM=,tag:fz0/g7CxKiTfNqBCN/gn9A==,type:int]
          discord_id: ENC[AES256_GCM,data:CVcc2oU1r5Jnf2oG3G0EyVoY,iv:jUbOixhXAkUXjGUgJ9T2GP/w4lDkp3Zfxvgm0jVAR3A=,tag:dbjIm0DG+EI1Wc5G5fGEqA==,type:int]
          label: ENC[AES256_GCM,data:6VfKKOU=,iv:3Wqx2QeqZwsVLp0U27jl8wXm4cbwPTIwIfbIz3al790=,tag:WA+XRCnmX/oVeTXStN95VQ==,type:str]
        - email: ENC[AES256_GCM,data:Lzjz9Y1nxd2Wnjt3cpoqpX2BWuvfmQ==,iv:MTUd5kDTsU13EYEcsgPxc7kh8t1L3oue/g8OFF/cyFo=,tag:r7xXQ7iEvfRSzAurWpgZRw==,type:str]
          permissions: ENC[AES256_GCM,data:yBoIhtShTek=,iv:eUP/u/HvL2y4Vrx9MMvC7DtH6vmD9THl6meCSTd5SAQ=,tag:y4nQ9nRNSlllGm4Aio/ZUQ==,type:int]
          label: ENC[AES256_GCM,data:9PXomkBj,iv:VOdcvob45UKoRn8ADGOGr/3H2DgDPlmRyUg9EuoHoXk=,tag:PtdBUm4r3f3OWN6GDYt4uw==,type:str]
          discord_id: ENC[AES256_GCM,data:A/WQhF4UFiFppA7RJKPtlSyr,iv:0mEhUTSYZOJtWp5eqHkWvg9KdlqoLzFW1t6e0d63D0E=,tag:k7/kWA+Gi7X/svtopWDThw==,type:int]
plex_secret:
    machine_id: ENC[AES256_GCM,data:DTuLhVQDFkMBeAExX+J0UyMbGUuZcaI/uHRgs7W9jSlKKD+L,iv:aZLAPeHH5DjzCsuEP4aDKLqDIdxJo637xMezSpPo0C4=,tag:6Jz2sCUqOXoO9FV72yrvPg==,type:str]
    claim_token: ENC[AES256_GCM,data:MRm1MZCX7VbkZL9vgRN3nZEPD6OmXd/7lcY=,iv:PHxVlJh8pSO/hqQCpAPOvbr7TAZTx/ICIFmt+kmkxAY=,tag:lQYbKKkny5LSrky5unzc8g==,type:str]
    online_token: ENC[AES256_GCM,data:sru4/mhdTcfAbvuN8C9ZqeeVJv8=,iv:e1U9274M6Pc66Ojx/KQTQEITyBWTAZcqCKK24cbSELQ=,tag:LmwdOTbKAPV/QBUUaBSNJQ==,type:str]
    processed_machine_id: ENC[AES256_GCM,data:S53IXy3aq/fV3fw/4ja64YqXV8t5f0hBw3RJ69JMLo1pEapBb/j9kg==,iv:6lSLwFwvIOS9CGXo4s6TDNH53k0U7swvMy8raN8cJAc=,tag:/JHmcGdv7hPcv3P3g2/qvA==,type:str]
    anonymous_machine_id: ENC[AES256_GCM,data:XtmX/9Szj5WWdPMsFvuSswf2z8GONdNmmv3BtyrtImdob0JK,iv:9gWEgKt5IXeZRXFdx5JCODfLoNlvs6majUOxVyffPvE=,tag:nZGFH+2HVEBsdzrbDY8EsA==,type:str]
    online_username: ENC[AES256_GCM,data:13dz6LFN47UoEw==,iv:5iUwI8GFYI3gz07BpLOV/QRQunu3Cwp8yIh/UP7C6vE=,tag:rwSm55fwEq+X9s76E9aLLg==,type:str]
    online_email: ENC[AES256_GCM,data:bHEi0g4s3JII0X/P2FaLpY2BQoFtDfk2j8A+,iv:SpgBzEAPVkGtyBlJYCcq99+PK/yGymxYJS0VRNtrR4E=,tag:M5HzNYP4+G4Cftvshd4BUw==,type:str]
tmdb_api_key: ENC[AES256_GCM,data:Qc8+9DuuHFoAydjmHwQ+qQOJKh/qvKppTuCysfuF+uQ=,iv:2Srs1Ce2hfX+63RK8Oe9XpQzrcay4c4zS4cVFJY6poM=,tag:yEwYgTXlBA4vbHzh23Ojmw==,type:str]
ssh_user_password: ENC[AES256_GCM,data:jn+XX40=,iv:s+Rrkl3cFLBGqDKq2SQHFmluHaHJAUctZS9EoeZY/1Y=,tag:DmIwLPOUsNq8o5r7F2uI5A==,type:str]
cleanuparr_secret:
    password_hash: ENC[AES256_GCM,data:DCg2yiRoHuMAYU4PayzWUvXUGjIRTg==,iv:T5SDVxeRnfudu8VbRsQed4Ix3otbwoHsZAaD5hdlAWs=,tag:ZY308E83Yl80kdO3FvDdsA==,type:str]
    api_key: ENC[AES256_GCM,data:Vm3eGJomk4IXztxCvZ5h+1OHlW5BtYC6qczceLjr2yvUZ8qCXyL8YjHgJDeEVfRbPOwHBib4p2nFeCaqRs/jbg==,iv:/9BOb+vuOLTZHvsT1KzDV2bGbwgwrsNT0aOf6Py8inc=,tag:pVP4aCklNhNED1uCOMSSpA==,type:str]
anki_secret:
    sync_user1: ENC[AES256_GCM,data:YCoVhUSCy0ZYaKlM9dAbUPqsz4B8uVEWIkI=,iv:itl/YYWU45DM1js3EdlSodxNLQIkDVlIeWLtj4WR2Gk=,tag:VRlWDLLwMWKGgaG+hMLuOw==,type:str]
    sync_user2: ENC[AES256_GCM,data:bDjisqoxJgpN7H4UFqu3/ymaApKn2tSaaiJv534=,iv:8u3TzZkXhNwxMILL3NVAzjCD23fNJxu9nQ5/hol+0+I=,tag:c3+4ES7Euiba97xGx36rNQ==,type:str]
restic_password: ENC[AES256_GCM,data:zq6T1QM7LpAWMyuVk9gWbhbhrvgtsjM3pU21dXOplX4U0VO0Bdew5jmhykc=,iv:kq3O517TNkS7YjSDvM7BYN4gKJU5OQCgGc5/VSxWZao=,tag:bd5Z0bzFYv5SmWixAH/ayQ==,type:str]
cloudflare_secret:
    purge_token: ENC[AES256_GCM,data:8yRSjWBKsF7EDkbPhklflTkX+8QY2Dvwj2MSJXwcw4HJWgwfjPr8OP+NiXTCaAuqnX4NhSU=,iv:6zW5iMG373fdhOx9s2CUW3/eVrhI7esYWx2I6jaQCKk=,tag:vAolJ1StCt/EhagQA68kcQ==,type:str]
discord_secret:
    bot_token: ENC[AES256_GCM,data:llv0uuqFIzSB2AkuqILEGI+pq89mxUeUCWlXLyluH+GIDeparMUKq7ZKMvxw1qnzyYLJMxT3gl/ZsY47JrnoapKDMujNJ3Hf,iv:C/5rcDEVemP/j/TFGfwufqBCd3hsm7dW8gi3NUVEE2c=,tag:lKshwHtTDEethKjC0i2DPA==,type:str]
sops:
    age:
        - recipient: age1wevrc2du2esx4p6td6ghn0rrw8ldg5zxszruxpn98q5ucj9ykqusduyt4m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZmxENmZxZ0dTWDNoemt5
            N2FDWFd5YUx0bnhjZG5SMFdFSUk3V3hLWkFrClp1UzFWRkdCYXFGYjNRUjhncDR3
            cDFYM0xYQVBEd3FZZ3V3V2VpOWI0QlEKLS0tIHVXL2RBcEZpS0d4QktOVGR3Q0o0
            bDM2YWxwQnpNYzZFckg3SDRoRUdTYkUKdcSPlhz2+GkdoyVgZiwOhcAqmFWXoRaQ
            FQRGihoGIRQzPpgiKmMCP1j5FQy9DqlvQM2/eK00kX5JbKxdfdy3Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T15:41:36Z"
    mac: ENC[AES256_GCM,data:B962E0h6OacBzVSiewzJtnnfHuewLQZlNSX9ivA8uRK0aSKIm2aQSMjX+eK4u+sVzF15z9nPH/qDu/GEeo6SDCmlFITyFN4WAkCLb2f0y4fin+59BZI5QpAjeJPcxo0ttMs3Fn+s8f3l8CbiN21fJDqfV26FpcCad3xF+lxMQ7A=,iv:OheqYDZXIcFUxwvMmYy3X2PD7pQa8hdNy4V4ZdOgFRc=,tag:87UXpn9iohoTDs/tiysWSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
