vpn_secret:
    provider: ENC[AES256_GCM,data:Pp9lW5Hz,iv:liOpvtQOw+Y+frETDyFAKj31ZRqPsEwL5H4amtDr+Zc=,tag:aThTwF2LtN+dsyRkiCOTCA==,type:str]
    private_key: ENC[AES256_GCM,data:SWr71FnykXl89ipChfILXnraLNwCQzzgQ0GpNuAUrEUwBnLkjTewfeTaiLo=,iv:nEE7n9e6HcxAFOm2IrU2EMTLR2lAZBbXwAJI/SeyJUQ=,tag:Swv3aC1aUOwVYJ8NIO0uMQ==,type:str]
    addresses: ENC[AES256_GCM,data:wepfmZfyS18uONA=,iv:QrBVfRacSZrIaX/j6qyVcDxKMflWB+ZaO/IUSKktIgI=,tag:fs1ZdTGXhSsZfLaxeI3oYQ==,type:str]
admin_password: ENC[AES256_GCM,data:EWnHx3e2Vg==,iv:MeTHxD5I1rYkF0Q3qCRma46MUZvFALl7cZyB6ye0ceI=,tag:lgWvaFgxbkhhvaJGQRyMhA==,type:str]
api_keys:
    sonarr: ENC[AES256_GCM,data:PNJGN1Eb+LVHzFhGjw42veEnEYlf3JnTrtvWCNEztMk=,iv:rbWjTr5MNJhx2T8fRZ1v6xZ69B6kincIWJPXR0LZ0JE=,tag:zT1cUyk9D+y7tW1+LBQ8Ow==,type:str]
    radarr: ENC[AES256_GCM,data:yVq6SK1egvcQ0zJ9EXxXuJ9uzOqUzbhkTAXU6U+D80Y=,iv:5tn8+3XHtbLpy3xp3g8pU5ibD9I4E3iyzJa3hEGpsZo=,tag:oRr1F7ESrPd6H3rvHnSgfQ==,type:str]
    prowlarr: ENC[AES256_GCM,data:Z9ThRpzHbzBKLr0luApioAJim4j2BQAiD/kL/fDVGhc=,iv:VTI+vBytR7iNT8M5TnAUQyP3w5PsVjul6yZatWYd/Q0=,tag:FgrL3dD+HxMrrKkjJds64A==,type:str]
overseerr_secret:
    vapid_private: ENC[AES256_GCM,data:mnx9wTrhJLhTxgr7XGiDNc8COEVVfEM8+fGwKp6m2DSRkVCDq0nEEv6y/A==,iv:1RDUSAYhXx1ZpcoNj+K2ETWkElHj2wjgLUwB5f/P8Ko=,tag:KyxPOYLCg2u75dwVzXccyQ==,type:str]
    vapid_public: ENC[AES256_GCM,data:OnTkRDN632b7rRvw1xxmEVIFVeUuk9zg39ANND8OszJOOtyB5givzLQvVBcNUVqcslzPs3dhQxOL7kXma8GyxWdZ8VY+6nmyLzvcFUzb8eOY4yijmdX6,iv:rwdCxbmdJcCRNtQcXG/hWOd2z6Ig+TylwyzRks1PtmY=,tag:rW7NH/UJAyZpivP4+oDWrA==,type:str]
    client_id: ENC[AES256_GCM,data:zqUZwyIkfXhKY1/ZCAO87b5cKsIlH/42ERlg6pBWU2VaF3EW,iv:kVUsn7qefmVYafYA+Om3xKm8qKYGKqJBU0bR7sYSFqI=,tag:yTuQSv5edhGXtwz1C8uv8g==,type:str]
    plex_machine_id: ENC[AES256_GCM,data:L1wbljh5ggv4WvCDGZsIfZVWOgcRI6m0tteVCWMvezatAFx2PVXrmQ==,iv:INmRIcVi43Z/sUEPKF1m73/I5ObtmzsJ1Cepw1lSzd8=,tag:pVP2UiX/kAco5XWbFQ7D/A==,type:str]
    plex_name: ENC[AES256_GCM,data:FhYMnhyvVIS+,iv:yQ5oevgjuUxn+4J5iYotcbZPWsQon3a2jFeIxtEWveo=,tag:CvSxliyXoAzDKLyyvtxpsQ==,type:str]
    api_key: ENC[AES256_GCM,data:WsZPdV9n8ci0HQWP8TxfCxNMjwCyI8a+AdoF1LlQGiYF0QKxcDLB3QkGqWCXQhEdix9onw/1DL03/X5ZUckn8NN45xA=,iv:tPN07IC9nibHea9DlO19LXZEhOHV3RF480x2fDlZBsE=,tag:VGt/lHKrDpZNawNO+S5SZg==,type:str]
    users:
        - email: ENC[AES256_GCM,data:frLLH3zufzAkmFkajyNc6Yj+dDXoGRgRtqNB,iv:am5XehobVnOJPzNqxX+ABINhLetdX18grXO9XKbkuo8=,tag:ieJcxEO4c0y8SpMScaFdaQ==,type:str]
          permissions: ENC[AES256_GCM,data:RA==,iv:/MZQjMUvP/F03NfFLZ7HvcOP6/Ro/frlr9v8MVTdHzo=,tag:gzFmH0R8GryefzPQNcQWkg==,type:int]
        - email: ENC[AES256_GCM,data:AreCe1XpRiVS4I0AOCW7alsEEqZoLQ==,iv:SP545HmZN0Bf0ZSeAy+sPzRmPdzHmJ+q93NxET1/tj0=,tag:ZSKv0KqLkrcVU91MP+Z+Fg==,type:str]
          permissions: ENC[AES256_GCM,data:SkfKUg==,iv:Egr2Y4kcc1jvTK5W7ZfS6uNJ6AXoCI2KGam9hneOhsw=,tag:bSp+EqTDZPM0pMsKLQaIGw==,type:int]
          label: ENC[AES256_GCM,data:zSHoCmvs,iv:N/voHmCUeAwUfNI4l3s6PzRDdZq6s9rNwRHXthqxBuM=,tag:exLco2PeHLKmiztnt83Crw==,type:str]
plex_secret:
    machine_id: ENC[AES256_GCM,data:DTuLhVQDFkMBeAExX+J0UyMbGUuZcaI/uHRgs7W9jSlKKD+L,iv:aZLAPeHH5DjzCsuEP4aDKLqDIdxJo637xMezSpPo0C4=,tag:6Jz2sCUqOXoO9FV72yrvPg==,type:str]
    claim_token: ENC[AES256_GCM,data:MRm1MZCX7VbkZL9vgRN3nZEPD6OmXd/7lcY=,iv:PHxVlJh8pSO/hqQCpAPOvbr7TAZTx/ICIFmt+kmkxAY=,tag:lQYbKKkny5LSrky5unzc8g==,type:str]
    online_token: ENC[AES256_GCM,data:sru4/mhdTcfAbvuN8C9ZqeeVJv8=,iv:e1U9274M6Pc66Ojx/KQTQEITyBWTAZcqCKK24cbSELQ=,tag:LmwdOTbKAPV/QBUUaBSNJQ==,type:str]
    processed_machine_id: ENC[AES256_GCM,data:S53IXy3aq/fV3fw/4ja64YqXV8t5f0hBw3RJ69JMLo1pEapBb/j9kg==,iv:6lSLwFwvIOS9CGXo4s6TDNH53k0U7swvMy8raN8cJAc=,tag:/JHmcGdv7hPcv3P3g2/qvA==,type:str]
    anonymous_machine_id: ENC[AES256_GCM,data:XtmX/9Szj5WWdPMsFvuSswf2z8GONdNmmv3BtyrtImdob0JK,iv:9gWEgKt5IXeZRXFdx5JCODfLoNlvs6majUOxVyffPvE=,tag:nZGFH+2HVEBsdzrbDY8EsA==,type:str]
    online_username: ENC[AES256_GCM,data:13dz6LFN47UoEw==,iv:5iUwI8GFYI3gz07BpLOV/QRQunu3Cwp8yIh/UP7C6vE=,tag:rwSm55fwEq+X9s76E9aLLg==,type:str]
    online_email: ENC[AES256_GCM,data:bHEi0g4s3JII0X/P2FaLpY2BQoFtDfk2j8A+,iv:SpgBzEAPVkGtyBlJYCcq99+PK/yGymxYJS0VRNtrR4E=,tag:M5HzNYP4+G4Cftvshd4BUw==,type:str]
tmdb_api_key: ENC[AES256_GCM,data:Qc8+9DuuHFoAydjmHwQ+qQOJKh/qvKppTuCysfuF+uQ=,iv:2Srs1Ce2hfX+63RK8Oe9XpQzrcay4c4zS4cVFJY6poM=,tag:yEwYgTXlBA4vbHzh23Ojmw==,type:str]
ssh_user_password: ENC[AES256_GCM,data:jn+XX40=,iv:s+Rrkl3cFLBGqDKq2SQHFmluHaHJAUctZS9EoeZY/1Y=,tag:DmIwLPOUsNq8o5r7F2uI5A==,type:str]
cleanuparr_secret:
    password_hash: ENC[AES256_GCM,data:DCg2yiRoHuMAYU4PayzWUvXUGjIRTg==,iv:T5SDVxeRnfudu8VbRsQed4Ix3otbwoHsZAaD5hdlAWs=,tag:ZY308E83Yl80kdO3FvDdsA==,type:str]
    api_key: ENC[AES256_GCM,data:Vm3eGJomk4IXztxCvZ5h+1OHlW5BtYC6qczceLjr2yvUZ8qCXyL8YjHgJDeEVfRbPOwHBib4p2nFeCaqRs/jbg==,iv:/9BOb+vuOLTZHvsT1KzDV2bGbwgwrsNT0aOf6Py8inc=,tag:pVP4aCklNhNED1uCOMSSpA==,type:str]
anki_secret:
    sync_user1: ENC[AES256_GCM,data:YCoVhUSCy0ZYaKlM9dAbUPqsz4B8uVEWIkI=,iv:itl/YYWU45DM1js3EdlSodxNLQIkDVlIeWLtj4WR2Gk=,tag:VRlWDLLwMWKGgaG+hMLuOw==,type:str]
    sync_user2: ENC[AES256_GCM,data:bDjisqoxJgpN7H4UFqu3/ymaApKn2tSaaiJv534=,iv:8u3TzZkXhNwxMILL3NVAzjCD23fNJxu9nQ5/hol+0+I=,tag:c3+4ES7Euiba97xGx36rNQ==,type:str]
restic_password: ENC[AES256_GCM,data:zq6T1QM7LpAWMyuVk9gWbhbhrvgtsjM3pU21dXOplX4U0VO0Bdew5jmhykc=,iv:kq3O517TNkS7YjSDvM7BYN4gKJU5OQCgGc5/VSxWZao=,tag:bd5Z0bzFYv5SmWixAH/ayQ==,type:str]
cloudflare_secret:
    purge_token: ENC[AES256_GCM,data:8yRSjWBKsF7EDkbPhklflTkX+8QY2Dvwj2MSJXwcw4HJWgwfjPr8OP+NiXTCaAuqnX4NhSU=,iv:6zW5iMG373fdhOx9s2CUW3/eVrhI7esYWx2I6jaQCKk=,tag:vAolJ1StCt/EhagQA68kcQ==,type:str]
sops:
    age:
        - recipient: age1wevrc2du2esx4p6td6ghn0rrw8ldg5zxszruxpn98q5ucj9ykqusduyt4m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZmxENmZxZ0dTWDNoemt5
            N2FDWFd5YUx0bnhjZG5SMFdFSUk3V3hLWkFrClp1UzFWRkdCYXFGYjNRUjhncDR3
            cDFYM0xYQVBEd3FZZ3V3V2VpOWI0QlEKLS0tIHVXL2RBcEZpS0d4QktOVGR3Q0o0
            bDM2YWxwQnpNYzZFckg3SDRoRUdTYkUKdcSPlhz2+GkdoyVgZiwOhcAqmFWXoRaQ
            FQRGihoGIRQzPpgiKmMCP1j5FQy9DqlvQM2/eK00kX5JbKxdfdy3Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T15:45:15Z"
    mac: ENC[AES256_GCM,data:xA/BUTWKXFStN1WabpPYyBDVPDxIhBVEkNhaeK5jRgi8yLTw+LxLsaO4s1T9Ls6TfghS8lk6VKdh6xYjOsyPU+NvLpBhi6tSek7VcsJBqEGF7nYnH8+ZS6a8YTbTnkPYf+RHk3lI1iQqJNGYkYNTuUjUk/hkLIb0IeEvHW1Lp1g=,iv:WZchKuGE1bJ48nScvm/LZhtdvusDgKhDhTYMtlHnOPk=,tag:Kbegi0Ljf0aeYYgFpooQxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
