events {}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        root /usr/share/nginx/html;

        location / {
            if ($arg_t = "caps") {
                rewrite ^ /ci-caps.xml break;
            }
            # Default to indexer for searches or other calls
            rewrite ^ /ci-indexer.xml break;
        }
    }
}
