---
- name: Template Overseerr settings file
  ansible.builtin.template:
    src: overseerr_settings.json.j2
    dest: "{{ config_root }}/overseerr/settings.json"
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: "0644"
